### ISSUE TITLE
How do I get this chipdb file: xc7a35t.bin?

### ISSUE THREAD

**Issue by JamesTimothyMeech** [daveshah1/nextpnr-xilinx#67]
I have followed the install instructions but I can't see any of the files that should populate `/xilinx-chipdb/xc7a35t.bin`. Which part of the install do I need to revisit to get these files?

Is there any command I can run to generate or download these files?

**Comment by VIPQualityPost** [comment]
You have to generate the database file and then create the .bin following the directions from "Building the Arty Example".
Get the database file by `git submodule init` and `git submodule update`.
then do:
`pypy3 xilinx/python/bbaexport.py --device xc7a35tcsg324-1 --bba xilinx/xc7a35t.bba`
`./bba/bbasm --l xilinx/xc7a35t.bba xilinx/xc7a35t.bin`

**Comment by JamesTimothyMeech** [comment]
Thanks!
